# General  
experiment_name: exp04 
train_2d: False
no_eval: False
finetune: False

# Traning 
epochs: 50
checkpoint_frequency: 10
batch_size: 32 
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
data_root: data/EgoMotion/
config: data/EgoMotion/meta_remy.yml
image_tmpl: "{:04d}.jpg"
train_size: 8000
val_size: 50
clip_len: 16
data_stride: 81
rootrel: True
sample_stride: 1
num_joints: 17
use_slam: True
gt_2d: False

# Loss
lambda_3d_velocity: 0.5
lambda_scale: 0.5
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0
