# General  
experiment_name: global_exp01 
dataset: "kinpoly"
no_eval: False
finetune: False

# Traning 
epochs: 50
checkpoint_frequency: 10
batch_size: 8 
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
data_root: /data/newhome/litianyi/dataset/kin_poly/MoCap_dataset/
config: /data/newhome/litianyi/dataset/kin_poly/MoCap_dataset/mocap_meta.yml
image_tmpl: "{:05d}.jpg"
rot_represent: "rot6d"
train_size: 10000
val_size: 3000
clip_len: 16
data_stride: 81
rootrel: True
sample_stride: 1
num_joints: 17
use_slam: True
use_depth: True
gt_2d: False

# Loss
trans_scale: 1
trans_v_scale: 0.5
rot_scale: 1.5
rot_v_scale: 0.5
